aseduis_egresados_homepage:
    path:     /hello/{name}
    defaults: { _controller: AseduisEgresadosBundle:Default:index }

aseduis_egresados_crear:
    path:     administrador/egresados/crear
    defaults: { _controller: AseduisEgresadosBundle:Egresados:Crear }

aseduis_egresados_modificar:
    path:     administrador/egresados/modificar/{id}
    defaults: { _controller: AseduisEgresadosBundle:Egresados:Modificar }

aseduis_egresados_eliminar:
    path:     administrador/egresados/eliminar/{id}
    defaults: { _controller: AseduisEgresadosBundle:Egresados:Eliminar }

aseduis_egresados_buscar:
    path:     administrador/egresados/buscar
    defaults: { _controller: AseduisEgresadosBundle:Egresados:Buscar }

aseduis_egresados_ver:
    path:     administrador/egresados/ver/{id}
    defaults: { _controller: AseduisEgresadosBundle:Egresados:Ver }

aseduis_egresados_administrador_crear:
    path:     administrador/administrador/crear
    defaults: { _controller: AseduisEgresadosBundle:Administrador:Crear }

aseduis_egresados_administrador_modificar:
    path:     administrador/administrador/modificar/{id}
    defaults: { _controller: AseduisEgresadosBundle:Administrador:Modificar }

aseduis_egresados_administrador_eliminar:
    path:     administrador/administrador/eliminar/{id}
    defaults: { _controller: AseduisEgresadosBundle:Administrador:Eliminar }

aseduis_egresados_administrador_buscar:
    path:     administrador/administrador/buscar
    defaults: { _controller: AseduisEgresadosBundle:Administrador:Buscar }
