aseduis_frontal:
    resource: "@AseduisFrontalBundle/Resources/config/routing.yml"
    prefix:   /

aseduis_eventos:
    resource: "@AseduisEventosBundle/Resources/config/routing.yml"
    prefix:   /

aseduis_egresados:
    resource: "@AseduisEgresadosBundle/Resources/config/routing.yml"
    prefix:   /

aseduis_user:
    resource: "@AseduisUserBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
