aseduis_frontal_homepage:
    path:     /hello/{name}
    defaults: { _controller: AseduisFrontalBundle:Default:index }

aseduis_frontal_index:
    pattern:  /
    defaults: { _controller: AseduisFrontalBundle:Index:index }
 
#Recibe el id correspondiente al iddepartamento del modelo Departamento
aseduis_frontal_general_buscarciudad:
    pattern:  generar/buscarCiudad/{id}.{funcion}
    defaults: { _controller: AseduisFrontalBundle:General:Buscarciudad }
    
#Recibe el id correspondiente al idtipoprogramaacademico del modelo Tipoprogramaacademico
aseduis_frontal_general_buscarprogramaacademico:
    pattern:  generar/buscarProgramaacademico/{id}.{funcion}
    defaults: { _controller: AseduisFrontalBundle:General:Buscarprogramaacademico }
    
#Recibe el id correspondiente al idtipoprogramaacademico del modelo Tipoprogramaacademico
aseduis_frontal_general_buscarprogramaacademicoegresado:
    pattern:  generar/buscarProgramaacademicoEgresado/{id}
    defaults: { _controller: AseduisFrontalBundle:General:Buscarprogramaacademicoegresado }
