parameters:
#    aseduis_eventos.example.class: Aseduis\EventosBundle\Example

services:
#    aseduis_eventos.example:
#        class: %aseduis_eventos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
